# Generated by Django 2.0.6 on 2020-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titles', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parnt_elevel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_title',
                'managed': False,
            },
        ),
    ]
