# Generated by Django 2.0.6 on 2020-11-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
