# Generated by Django 2.0.6 on 2020-11-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201104_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='salt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
